CREATE TABLE companies (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
    code NVARCHAR(255) NOT NULL,
    website NVARCHAR(255) NOT NULL DEFAULT(''),
    email NVARCHAR(255) NOT NULL,
    address NVARCHAR(255) NOT NULL,
    created_at DATETIME2 NOT NULL DEFAULT(GETUTCDATE()),
    updated_at DATETIME2 NULL
);
